CREATE DATABASE passports_db;

CREATE TABLE passports
(
    series smallint NOT NULL,
    "number" integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_Passports" PRIMARY KEY (series, "number")
);

CREATE TABLE passportschangeshistory"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    series smallint NOT NULL,
    "number" integer NOT NULL,
    changetype boolean NOT NULL,
    date date NOT NULL,
    CONSTRAINT "PK_PassportsChangesHistory" PRIMARY KEY (id)
);

CREATE INDEX IX_PassportsChangesHistory_Date
    ON public.passportschangeshistory" USING btree
    (date ASC NULLS LAST)
    TABLESPACE pg_default;

INSERT INTO public.passports (series, "number")
SELECT i.m, j.n
FROM (SELECT * FROM generate_series(0, 999) AS s WHERE (((s % 100) > 96 AND (s % 100) < 100) OR ((s % 100) >= 0 AND (s % 100) < 25))) AS i(m),
generate_series(0, 999) AS j(n);

